image: maven:3.6.0-jdk-8-slim

pipelines:
  default:
    - step:
        caches:
          - maven
        script:
          - mvn -V -B clean install
          # -V triggers an output of the Maven and Java versions at the beginning of the build
          # -B batch mode makes Maven less verbose