name: release-to-maven-central

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Release to Maven Central
      run: |
       sudo apt-get update && sudo apt-get install -y gpg gpg-agent git --no-install-recommends
       export GPG_TTY=$(tty) # to fix the 'gpg: signing failed: Inappropriate ioctl for device', see https://github.com/keybase/keybase-issues/issues/2798#issue-205008630
       echo $GPG_SECRET_KEY | base64 --decode | gpg --batch --import # use 'batch' otherwise gpg2 is asking for a passphrase, see https://superuser.com/a/1135950
       echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust
       mvn -V -B -s settings.xml deploy -DskipRelease=false
       # ./release.sh # TODO
       # -V triggers an output of the Maven and Java versions at the beginning of the build
       # -B batch mode makes Maven less verbose
       # -s causes the usage of the local settings with the required credentials
      env:
        GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
        GPG_OWNERTRUST: ${{ secrets.GPG_OWNERTRUST }}
